#!/usr/bin/env ruby
require "fileutils"

src = ARGV[0]

if ARGV.size == 0
  puts "cpx: ファイルオペランドがありません"
elsif ARGV.size == 1
  puts "cpx: '#{src}' の後に宛先のファイルオペランドがありません"
else
  begin
    ARGV.each_with_index do |dest, index|
      if index == 0
        next
      end
      FileUtils.cp(src,dest)
    end
  rescue => error
    puts error.message
  end
end