#!/usr/bin/env ruby
require "fileutils"

file_to_copy = ARGV[0]

if ARGV.size < 2 
	puts "cpx コピー元 コピー先1 コピー先2……"
else
	begin
		Number_of_files_to_copy = ARGV.size - 1
		Number_of_files_to_copy.times do |i|
			file_to_duplicate = ARGV[i + 1]
			FileUtils.cp(file_to_copy,file_to_duplicate)
		end
	rescue
		puts "'#{file_to_copy}' No such file"
	end
end